{% set version = "1.1.0" %}

package:
  name: macha
  version: 0.1

source:
  git_url: https://github.com/akaupang/macha.git
  
build:
  norach: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv   

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pip
    - parmed
    - openbabel
    - natsort
    - re
